blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Mahmud0808/ColorBlendr/discussions
    about: Discuss anything related to ColorBlendr, or ask and answer questions here.
  - name: Telegram Channel
    url: https://t.me/DrDsProjects
    about: Follow telegram channel to get latest news and updates.
  - name: Telegram Group
    url: https://t.me/DrDsProjectsChat
    about: We recommend to go to this place if you wish to ask a question and want a quicker reply. 
