name: Crowdin Download

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:

  synchronize-with-crowdin:
    name: Download translations from Crowdin
    if: github.repository_owner == 'Mahmud0808'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate translators table
        id: "translators"
        uses: andrii-bodnar/action-crowdin-contributors@v2
        with:
          contributors_per_line: 6
          max_contributors: 500
          image_size: 32
          min_words_contributed: 1
          files: ./docs/translators.md
          crowdin_project_link: 'https://crowdin.com/project/ColorBlendr'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Save translators in assets
        run:
          printf '%s\n' '${{ steps.translators.outputs.json_report }}' > ./app/src/main/assets/translators.json

      - name: Download translations
        uses: crowdin/github-action@v2
        with:
          upload_translations: false
          upload_sources: false
          download_translations: true
          localization_branch_name: localization
          create_pull_request: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}